### PR TITLE
BMC Logo

### PR DESCRIPTION
**Pull request by shahed-al**
BMC has provided legal approval for the logo to be used on the INI Site

### CODE REVIEW

**Comment by xmulligan** [comment]
Thanks for adding. Can you commit this to the logos folder https://github.com/inclusivenaming/website/tree/main/static/img/logos

Also can you put down an email contact so we know who to reach once the legal part is sorted out?

**Comment by shahed-al** [comment]
contact email: shahed_alqadi@bmc.com

**Comment by xmulligan** [comment]
image
you actually added the image in the main directory rather than the logo folder. If you open up the folder, you can open the PR against that folder

**Comment by xmulligan** [comment]
@shahed-al can you close this since we already have #57 ?

**Pull request closed without merging**
