### PR TITLE
Add Splunk logo

### PR DESCRIPTION
**Pull request by wordsmeanstuff**

### CODE REVIEW

**Comment by edwarnicke** [comment]
Added @xmulligan who handles the various checks on adding logos :)

**Comment by wordsmeanstuff** [comment]
This message came from Splunk's legal team when I got permission for INI to include their logo. I don't think the brand guidelines matter here (Exhibit B), but do let me know if you need that. Thanks, Ed & Bill! 

> Splunk Inc. grants Inclusive Naming Initiative (the "Company") permission to use the Splunk trademarks and logo in the attached Exhibit A. The permission is only for use by the Company on their website listing Splunk as a participating organization.
> 
> The Splunk trademarks and logo may only be used for the above-identified purpose in line with our brand guidelines (Exhibit B) and shall not be used in any manner without further prior approval. Splunk may revoke the permission at any time, in its sole discretion, if the use is not in compliance with the usage requirements of this authorization.
> 
> Splunk is the exclusive owner of all right, title, and interest in the Splunk name, trademarks, logos, trade dress, software and user interfaces, and the Company’s use shall inure to Splunk's benefit.

**Comment by xmulligan** [comment]
Thanks @wordsmeanstuff ! If you can add a contact email, I'm happy to have it merged

**Comment by wordsmeanstuff** [comment]
Hey Bill, awesome! I'll serve as the point of contact for now between INI and legal/PR, so please use alyssa@wordsmeanstuff.com.

**Review by xmulligan — APPROVED** [review]

**Comment by celestehorgan** [comment]
I'm gonna merge this now and let's talk about blog posts now that KubeCon is over!

**Pull request merged**
