### PR TITLE
Replace PR 89 with this one

### PR DESCRIPTION
**Pull request by markcmiller86**
@Oshratn and @celestehorgan 

This PR should replace #89. Close #89 and work from this one instead.

- renames file correctly to `mark-miller-llnl-interview.md`
- fixes incorrect links in original
- various minor revisions for accuracy/clarity

I originally made proposed revisions [here](https://github.com/Oshratn/website/pull/1). There is no expectation on my part that @Oshratn accept *all* changes here...only those addressing inaccuracies. Sorry I didn't think to separate those from a second commit for clarity. If you would prefer that, lemme know.

### CODE REVIEW

**Comment by markcmiller86** [comment]
I am not sure what has happened with this? It seems to have been sitting here for 20+ days. I recall seeing somewhere that it was intended for Sept 8 to go live??

I am good with this now. How about others? @Oshratn @celestehorgan

**Comment by Oshratn** [comment]
Keeping an eye on this till the 8th and will push the button then.

**Comment by xmulligan** [comment]
Yes, it will be published on the 8th. Thanks for your work on this 💯

**Comment by xmulligan** [comment]
It is now live, please like and share 
https://twitter.com/inclusivenaming/status/1435556156043370498
https://www.linkedin.com/posts/inclusive-naming_moving-the-needle-on-inclusive-language-activity-6841321935163428865-eWTX

**Pull request merged**
