### PR TITLE
Add machine parsable DCI Lint configuration

### PR DESCRIPTION
**Pull request by petermetz**
The contents are derived from the recommendations
of the INI and are a direct translation of those
into JSON with a specific schema that DCI Lint expects.

Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

### CODE REVIEW

**Comment by pritianka** [comment]
Hello @petermetz - thank you for your work here! The team at INI is heads down with KubeCon + CloudNativeCon activities atm and would like to invite you to our next general meeting to chat about this. If you join our mailing list, you will be automatically added to the invite for 9:15 AM PT meetings on alternate Mondays (the next one is on May 17th). If you do not prefer to join the mailing list, I can send you the invite to the meeting if you let me know what email to use. Thanks!

**Comment by petermetz** [comment]
@pritianka Thank you for the info! I signed up to the mailing list and will attend the call on the 17th.

**Comment by petermetz** [comment]
@pritianka Just double checking: After having signed up to the mailing list, my calendar shows the meetings being held on the 10th, 24th, etc, not the 17th. Did the schedule change by any chance?

**Comment by edwarnicke** [comment]
@petermetz This may help: https://inclusivenaming.org/calendar/ :)

**Comment by petermetz** [comment]
> @petermetz This may help: https://inclusivenaming.org/calendar/ :)

@edwarnicke Cheers, that did it indeed. For some reason the only meeting my calendar saw was the OOS workstream, but now I got the full picture, thank you!

**Comment by celestehorgan** [comment]
I merged this because it's been sitting for so long. Let's talk about moving it at a future date.

**Pull request merged**
