### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by JimStLeger**
Logo for Splunk (via Alyssa Yell) to add on to "participating organizations" section of home page.

### CODE REVIEW

**Comment by edwarnicke** [comment]
@xmulligan Can you handle the process for this?

@JimStLeger Is there a reason this is a Draft PR instead of a normal PR?

**Comment by JimStLeger** [comment]
I started a draft PR for the Splunk logo. I only got as far as uploading their logo. I have not gotten to editing the html to insert the Splunk info. And to be honest, between yesterday and today (when I had an overseeing helper yesterday) I cannot find where that html code is. But I’ll look again once I get dinner/dishes/kids/dog done.

Thanks,
Jim

**Comment by xmulligan** [comment]
@JimStLeger it goes in layouts/shortcodes/logos.html

**Review by gkarthiks — APPROVED** [review]

**Comment by xmulligan** [comment]
@JimStLeger can you close this since we have #66 merged?

**Review by celestehorgan — APPROVED** [review]

**Pull request merged**
