### PR TITLE
Update logos.html

### PR DESCRIPTION
**Pull request by JimStLeger**
Apply PR after uploaded intel.svg logo file.

### CODE REVIEW

**Comment by xmulligan** [comment]
@JimStLeger can you confirm that you have legal sign off for this and list a contact person and email?

**Review by xmulligan — APPROVED** [review]

**Review by mschnoor-intel — APPROVED** [review]

**Comment by celestehorgan** [comment]
The preview is still broken because it hasn't been rebased – I'm going to merge this (as the requisite  files are merged) and keep an eye on it to correct any issues if they arise :)

**Comment by JimStLeger** [comment]
I have obtained a sign-off from the appropriate folks at Intel regarding adding our company's logo onto the INI website. Intel VP Melissa Evers-Hood has approved it. Let me know what else is required to finish this PR.

**Comment by xmulligan** [comment]
@JimStLeger already merged :)

**Pull request merged**
